version: "3.7"

services:
  ris-image:
    image: 'ris_4'
    build:
      context: .
      dockerfile: Dockerfile

  grpc:
    image: 'ris_4'
    ports:
      - 50051:50051
    command: python -m ris_4.server
    depends_on:
      - zookeeper
      - kafka

  worker:
    image: 'ris_4'
    command: sh -c 'sleep 5 && python -m ris_4.worker'
    depends_on:
      - zookeeper
      - kafka

  zookeeper:
    logging:
      driver: none
    image: bitnami/zookeeper:3.6.2
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    logging:
      driver: none
    image: bitnami/kafka:2.6.0
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"