# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ris_4.server.grpc.ris_4_pb2 as ris__4__pb2


class RIS4ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DecreaseByOneLetter = channel.unary_unary(
                '/ris_4.RIS4Service/DecreaseByOneLetter',
                request_serializer=ris__4__pb2.DecreaseByOneLetterRequest.SerializeToString,
                response_deserializer=ris__4__pb2.DecreaseByOneLetterResponse.FromString,
                )


class RIS4ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DecreaseByOneLetter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RIS4ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DecreaseByOneLetter': grpc.unary_unary_rpc_method_handler(
                    servicer.DecreaseByOneLetter,
                    request_deserializer=ris__4__pb2.DecreaseByOneLetterRequest.FromString,
                    response_serializer=ris__4__pb2.DecreaseByOneLetterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ris_4.RIS4Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RIS4Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DecreaseByOneLetter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ris_4.RIS4Service/DecreaseByOneLetter',
            ris__4__pb2.DecreaseByOneLetterRequest.SerializeToString,
            ris__4__pb2.DecreaseByOneLetterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
